# Colors, screen dimensions, gameplay constants
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)
WIDTH = 720
HEIGHT = 360
MIDLE_WIDTH = 30
MIDLE_LEFT = WIDTH // 2 - MIDLE_WIDTH // 2
MIDLE_HEIGHT = HEIGHT
SPACESHIP_WIDTH = 55
SPACESHIP_HEIGHT = 40
FPS = 60
VEL = 5
BORDER_WIDTH = 10
SHOOTING_DELAY_MS = 100
MAX_BULLETS = 3

# EXPERIMENTS:


HIT_REWARD = 0
SURVIVAL_REWARD = 0
STEP_REWARD = 0
WIN_BONUS = 0
MOVEMENT_REWARD = 0

TRAINED_MODEL = "best.pickle"
CHECKPOINT = "neat-checkpoint-"
RESUME_GENERATIONS = 1
NEW_GENERATIONS = 50
